WITH CTE AS (
    SELECT MEMBER_ID, LABEL, MODIFIED_ON,
           ROW_NUMBER() OVER(PARTITION BY MEMBER_ID, LABEL ORDER BY MODIFIED_ON DESC) AS RowNum
    FROM MEMBER_ADDRESS
)
DELETE FROM CTE
WHERE RowNum > 1;

CREATE UNIQUE INDEX IX_Unique_Member_Address
ON MEMBER_ADDRESS (MEMBER_ID, LABEL);